module.exports = {
  VITE_API_URL: "https://staging-api.example.com/api",
  VITE_API_NOTIFICATIONS_ENDPOINT: "https://staging-api.example.com/idiwebsocket",
  VITE_API_POLLING_INTERVAL: "60000",
  VITE_NOTIFICATION_TIMEOUT_DEFAULT: "10000",
  VITE_NOTIFICATION_TIMEOUT_URL_HTML: "20000",
  VITE_NOTIFICATION_TIMEOUT_COINS: "15000",
  VITE_NOTIFICATION_TIMEOUT_ERROR: "15000",
  VITE_NOTIFICATION_WIDTH: "400",
  VITE_NOTIFICATION_POSITION_BOTTOM: "10",
  VITE_NOTIFICATION_POSITION_RIGHT: "10",
  VITE_NOTIFICATION_GAP: "10",
  VITE_WINDOW_WIDTH: "420",
  VITE_WINDOW_HEIGHT: "600",
  VITE_WINDOW_MARGIN: "20",
  VITE_LOG: "true",
  VITE_OPEN_DEV_TOOLS: "false",
  NODE_TLS_REJECT_UNAUTHORIZED: "1" // Enable SSL certificate validation in staging
}; 